[package]
name = "test_derive_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tile-derive = { version = "0.1.0", path = "tile-derive" }
